### ISSUE TITLE
Workflow suggestion: edit LaTeX file somewhere else (Load file)

### ISSUE THREAD

**Issue by Splines** [Jonathan-LeRoux/IguanaTex#67]
I am aware that there is the `Open in external editor` command. However, consider the following workflow I'd like to use:

- I have an already-existing LaTeX project somewhere with custom definitions and a long preamble included in the `main.tex` file.
- I create a `main.pptx.tex` file next to the `main.tex` file where I remove all the `\input{}` commands to my sections and stuff like `tableofcontents`. In the end, I might have something like the following left. Note that the `\input{preamble}` refers to the file `preamble.tex` file residing next to the `main.tex` file.

```latex
\documentclass{article}
\input{preamble}
\input{defs}
\input{prettify-math}
\pagestyle{empty}
\begin{document}

Let $\epsilon > 0$.

\end{document}

```
- My preferred workflow would be to have this `main.pptx.tex` file as default file path in IguanaTex (also see issue #66). Ideally, I wouldn't even have to click on `Load File`. Instead, I could just have one shortcut, to read this files content and insert it as shape in PowerPoint. This way, I could quickly paste parts of my already existing LaTeX project into this `main.pptx.tex` file and use all the packages already defined in the preamble.

## Challenges/Wishes
- [ ] Loading a file would also have to instruct the LaTeX compiler where the base directory is, such that relative imports such as `\input{preamble}` are correctly resolved.
- [ ] Use the same file path to `main.pptx.tex` as default when generating (see issue #66).
- [ ] Don't require users to click on `Load File`.

**Comment by Jonathan-LeRoux** [comment]
It seems to me that setting the default Temp folder and load file path (as in #66) effectively implement this, apart from two differences:
1) the default Temp folder and file path are the same for all PowerPoint presentations, instead of depending on the presentation
2) one needs to click on `New LaTeX Display` then "Load File & Generate" (2 clicks) instead of having a dedicated button

Arguably, one typically works on a single presentation for a while, so it's not so bad to change the defaults once, and I'm thus not inclined to fix 1). It's also not clear how to save this setting "per .pptx" (or it would have to be a default inferred from the .pptx name).
Re: 2), I'm also not sure it's a mainstream enough feature to expose a button to all users. I guess I could make it into a Macro without a button, which could be added to the Quick Access Toolbar (on Windows only for now, unfortunately).

**Comment by Splines** [comment]
1) Yeah, that's not so important to me either. As you said: typically, one "works on a single presentation for a while".
Just being able to set a global default path is great.

2) That macro on Windows would be much appreciated ;) Then my workflow would literally be: change something in your favorite LaTeX editor and use one single shortcut to insert it in PowerPoint, that'd be blazing fast.

**Comment by Jonathan-LeRoux** [comment]
Please try this version: [IguanaTex_v1_61_1_20240731.zip](https://github.com/user-attachments/files/16444410/IguanaTex_v1_61_1_20240731.zip)
The macro is called "LoadDefaultFileAndGenerate".

**Comment by Jonathan-LeRoux** [comment]
Alright, here is a version with a dedicated button: [IguanaTex_v1_62.zip](https://github.com/user-attachments/files/16446183/IguanaTex_v1_62.zip)
Please let me know how it works.

**Comment by Splines** [comment]
Thank you, works great and exactly what I needed!

The error when an invalid file path is set and you click on `Generate from default .tex file` is currently:

> You need to set an existing LaTeX file as Default file path using "Make Default" in the Editor Window's "Read from file" pane.

Suggestions:
- "default file path" instead of "Default file path" (small "d")
- "editor window's [...]" (editor and window small)
- 'in the editor window's "Read from file" pane' -> I had to read twice to get what you meant with "editor window". Maybe replace with '[...] using "Make Default" in the IguanaTeX "Read from file" pane'?

**Comment by Splines** [comment]
> It seems to me that setting the default Temp folder and load file path (as in https://github.com/Jonathan-LeRoux/IguanaTex/issues/66) effectively implement this, apart from two differences: [...]

I think a third difference is that relative imports in the default file are not correctly resolved, e.g. `\input{preamble}` (where `preamble.tex` is sitting right next to the default file) will lead to the LaTeX error "File not found".

**Comment by Jonathan-LeRoux** [comment]
Thanks for these comments, they should be addressed in this version: [IguanaTex_v1_62_20240801.zip](https://github.com/user-attachments/files/16460930/IguanaTex_v1_62_20240801.zip)
Regarding the preamble, the Temp folder would have to be the folder where the default file is. I'll have to explain that somewhere.

**Comment by Jonathan-LeRoux** [comment]
Fixed with [v1.62 release](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.62).
